import 'package:flutter/cupertino.dart';
import 'package:movie_app/data/vos/actor_vo.dart';
import 'package:movie_app/data/vos/genre_vo.dart';
import 'package:movie_app/data/vos/movie_vo.dart';

List<MovieVO> getMockMoviesForTest() {
  return [
    MovieVO(
      false,
      "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
      [28, 12, 878],
      634649,
      "en",
      "Spider-Man: No Way Home",
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
      8426.2,
      "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
      "2021-12-15",
      "Spider-Man: No Way Home",
      false,
      8.2,
      10923,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      isPopular: true,
      isTopRated: false,
      isNowPlaying: false,
    ),
    MovieVO(
      false,
      "/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
      [16, 10751, 35, 14],
      508947,
      "en",
      "Turning Red",
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
      8326.002,
      "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
      "2022-03-01",
      "Turning Red",
      false,
      7.5,
      1374,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      isPopular: true,
      isTopRated: false,
      isNowPlaying: false,
    ),
    MovieVO(
      false,
      "/t7I942V5U1Ggn6OevN75u3sNYH9.jpg",
      [28, 53],
      760868,
      "sv",
      "Svart krabba",
      "To end an apocalyptic war and save her daughter, a reluctant soldier embarks on a desperate mission to cross a frozen sea carrying a top-secret cargo.",
      3649.07,
      "/mcIYHZYwUbvhvUt8Lb5nENJ7AlX.jpg",
      "2022-03-18",
      "Black Crab",
      false,
      6.1,
      248,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      isPopular: true,
      isTopRated: false,
      isNowPlaying: false,
    ),
  ];
}

List<ActorVO> getMockActors() {
  return [
    ActorVO(
      id: 224513,
      adult: false,
      knownFor: [],
      popularity: 130.756,
      name: "Ana de Armas",
      profilePath: "/14uxt0jH28J9zn4vNQNTae3Bmr7.jpg",
    ),
    ActorVO(
      id: 1136406,
      adult: false,
      knownFor: [],
      popularity: 109.117,
      name: "Tom Holland",
      profilePath: "/bBRlrpJm9XkNSg0YT5LCaxqoFMX.jpg",
    ),
    ActorVO(
      id: 2201315,
      adult: false,
      knownFor: [],
      popularity: 104.904,
      name: "Emma Mackey",
      profilePath: "/9OZBcFSS3Yz0Oqr8mssbQa4suW8.jpg",
    ),
  ];
}

List<GenreVO> getMockGenres() {
  return [
    GenreVO(id: 1, name: "Action"),
    GenreVO(id: 2, name: "Adventure"),
    GenreVO(id: 3, name: "Comedy"),
  ];
}

List<ActorVO> getMockCredits() {
  return [
    ActorVO(
      adult: false,
      id: 90633,
      knownForDepartment: "Acting",
      name: "Gal Gadot",
      popularity: 67.476,
      castId: 2,
      character: "Diana Prince / Wonder Woman",
      creditId: "595686e4c3a368382e050da4",
      order: 0,
      originalName: "Gal Gadot",
      profilePath: "/plLfB60M5cJrnog8KvAKhI4UJuk.jpg",
    ),
    ActorVO(
      adult: false,
      id: 62064,
      knownForDepartment: "Acting",
      name: "Chris Pine",
      popularity: 29.581,
      castId: 15,
      character: "Steve Trevor",
      creditId: "5b0b4526c3a3684adc0097a5",
      order: 1,
      originalName: "Chris Pine",
      profilePath: "/ipG3BMO8Ckv9xVeEY27lzq975Qm.jpg",
    ),
    ActorVO(
      adult: false,
      id: 41091,
      knownForDepartment: "Acting",
      name: "Kristen Wiig",
      popularity: 11.596,
      castId: 12,
      character: "Barbara Minerva / Cheetah",
      creditId: "5a975236c3a36861510077f1",
      order: 2,
      originalName: "Kristen Wiig",
      profilePath: "/N517EQh7j4mNl3BStMmjMN6hId.jpg",
    ),
  ];
}
